spring:
  application:
    name: api-user

  profiles:
    active: local #Local, Dev, Prod 등으로 프로필 구분하여 환경 설정 할 수 있다.

  config:
    import:
      - db-config.yml

jwt:
  access-token:
    expire: 30m
  refresh-token:
    expire: 14d
  secret: jwtwhatevertokenjwtwhatevertokenjwtwhatevertoken

server:
  port: 8081