name: Java CI For Test with Gradle

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375


    # 위 설정대신 github actions 의 아래 설정을 통해 사용할 수도 있다.
    # - name: Build and push Docker image
    #        uses: docker/build-push-action@v2
    #        with:
    #          push: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test --no-daemon --refresh-dependencies --stacktrace

      - name: Run Unit Tests
        run: ./gradlew UnitTest

      - name: Run E2E Tests
        run: ./gradlew E2eTest
        env:
          TESTCONTAINERS_HOST_OVERRIDE: localhost
          DOCKER_HOST: tcp://localhost:2375